# Dockerfile for Backend
FROM python:3.8.10-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Create and set working directory
RUN mkdir /app
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy application code
COPY . /app/

# Expose the port
EXPOSE ${PORT}

# Start the application
CMD ["./backend_start.sh"]
