# Dockerfile for Frontend
FROM node:16

# Set working directory
WORKDIR /app

# Install global dependencies
RUN npm install -g @quasar/cli

# Copy application code
COPY . /app/

# Install project dependencies
RUN npm install

# Expose the port
EXPOSE ${PORT}

# Start the application
CMD ["./web_start.sh"]
