version: '3.9'

networks:
  basic:

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
      target: front
    container_name: greaterwms_front
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - backend
    volumes:
      - ./templates:/GreaterWMS/templates:rw
      - ./web_start.sh:/GreaterWMS/templates/web_start.sh
    networks:
      - basic

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: greaterwms_backend
    restart: always
    volumes:
      - ./:/GreaterWMS/:rw
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - '8000:8000'  # Changed to 8000 (standard Django port)
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - basic
